"use client";

import React from "react";
import { FileText, Tag } from "lucide-react";

interface CaseSARPanelProps {
  dossier: string;
  typologyClassification: string;
  typologyRationale: string;
  decision?: string;
  caseId: string;
  alertId: string;
  entityId: string;
}

export function CaseSARPanel({
  dossier,
  typologyClassification,
  typologyRationale,
  decision,
  caseId,
  alertId,
  entityId,
}: CaseSARPanelProps) {
  return (
    <div className="space-y-4">
      {/* Case Header */}
      <div className="bg-slate-800/60 border border-slate-700/60 rounded-xl p-4">
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: "Case ID", value: caseId },
            { label: "Alert ID", value: alertId },
            { label: "Entity ID", value: entityId },
          ].map((f) => (
            <div key={f.label}>
              <p className="text-xs text-slate-400 mb-0.5">{f.label}</p>
              <p className="text-sm font-mono font-semibold text-white">{f.value || "—"}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Typology */}
      <div className="bg-slate-800/60 border border-slate-700/60 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-3">
          <Tag className="w-4 h-4 text-purple-400" />
          <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-widest">
            AML Typology
          </h3>
        </div>
        <div className="flex items-center gap-3 mb-3">
          <span className="bg-purple-500/20 border border-purple-500/40 text-purple-300 text-sm font-bold px-3 py-1.5 rounded-lg font-mono">
            {typologyClassification || "Pending"}
          </span>
          {decision && (
            <span
              className={`text-sm font-bold px-3 py-1.5 rounded-lg border ${
                decision === "BLOCK"
                  ? "bg-red-500/20 border-red-500/40 text-red-300"
                  : decision === "REVIEW"
                  ? "bg-amber-500/20 border-amber-500/40 text-amber-300"
                  : "bg-emerald-500/20 border-emerald-500/40 text-emerald-300"
              }`}
            >
              {decision}
            </span>
          )}
        </div>
        {typologyRationale && (
          <p className="text-sm text-slate-300 leading-relaxed">{typologyRationale}</p>
        )}
      </div>

      {/* SAR Dossier */}
      <div className="bg-slate-800/60 border border-slate-700/60 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-3">
          <FileText className="w-4 h-4 text-cyan-400" />
          <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-widest">
            SAR Dossier Narrative
          </h3>
        </div>
        {dossier ? (
          <div className="prose prose-invert prose-sm max-w-none">
            <div
              className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap font-mono text-xs bg-slate-900/60 rounded-lg p-4 border border-slate-700/40 max-h-96 overflow-y-auto"
            >
              {dossier}
            </div>
          </div>
        ) : (
          <div className="text-center py-8 text-slate-500">
            <FileText className="w-8 h-8 mx-auto mb-2 opacity-40" />
            <p className="text-sm">SAR narrative will appear after investigation completes</p>
          </div>
        )}
      </div>

      {/* Regulatory Note */}
      <div className="bg-slate-900/60 border border-slate-700/30 rounded-xl p-4">
        <p className="text-xs text-slate-500 leading-relaxed">
          ⚖️ <strong className="text-slate-400">Regulatory Note:</strong> This SAR narrative is AI-generated by the Fin-Spectra investigation engine for investigator review. All findings should be validated by a qualified AML compliance officer before regulatory filing. The system does not make final filing decisions.
        </p>
      </div>
    </div>
  );
}
